### ISSUE TITLE
(Github Comment Enhancer) Existing comment/note edit mode: add a Preview tab

### ISSUE THREAD

**Issue by tophf** [jerone/UserScripts#10]
Adding a Preview tab to the edit mode for an existing comment/note/issue on github.com would make editing more productive, while currently we are forced to 1. copy the text 2. click the Add new comment/note form 3. paste the text 4. click the Preview tab.

P.S. Just found your script, nice stuff, thanks!

**Comment by jerone** [comment]
[**@tophf**](https://github.com/tophf) commented on [29 aug. 2014 20:36 CEST](https://github.com/jerone/UserScripts/issues/10#issuecomment-53914260 "2014-08-29T18:36:29Z - Replied by Github Comment Enhancer"):
> > Keeping up with the rate Github is releasing new features and fixes recently, I wouldn't be surprised they fix it soon
> 
> Agreed.
> Especially if we harass the github feedback more :laughing:

I don't know when, but I just noticed that they fixed this issue. You can now edit inline comments with a preview tab.

**Comment by jerone** [comment]
Snippet for self:
```
$.ajax({
url: "https://github.com/jerone/UserScripts/wiki/_preview",
data: {text: "**Welcome**+to+_the_+UserScripts+wiki!"},
success:function(){
console.log('complete', arguments);
},
headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                'X-CSRF-Token': $0.closest('form').elements.authenticity_token.value 
            },
method: "POST"
});
```

**Comment by jerone** [comment]
Cool. Also learned they already do the ajax call to convert to markdown when you _hover_ over the preview tab.
