### ISSUE TITLE
(Github News Feed Filter) Not Working

### ISSUE THREAD

**Issue by dufferzafar** [jerone/UserScripts#101]
**Script**: Github News Feed Filter (Latest on GH)
**Browser**: Firefox 43.0.4
**Addon**: Scriptish 
**Error Message**: None
**Screenshot**: -
**Description**: I've installed the userscript, and reload github but the feed filter doesn't appear!

**Comment by jerone** [comment]
[Scriptish](https://github.com/scriptish/scriptish/) hasn't been updated in more then a year, with [bugs pilling up](https://github.com/scriptish/scriptish/issues)! I recently removed Scriptish from my installation as it keeps crashing on me. It was a very promising project, but for now I'm not supporting it anymore. On the other hand, [GreaseMonkey](https://github.com/greasemonkey/greasemonkey/) is getting [regular updates](https://github.com/greasemonkey/greasemonkey/commits/master) and will work on the upcoming [e10s](https://wiki.mozilla.org/Electrolysis).
