### ISSUE TITLE
(Github Comment Enhancer) pressing 'Ok' inside the "Link" and "Image" popups doesn't create the relevant tags (also 'Cancel' works neither)

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#102]
_(using GCE 2.9.0 in FF 45.0.1 x64 with GM 3.7 in win10 x64)_

When you either press the `Link` or `Image` buttons 
and you type something in the two textboxes in the popup,
then pressing `Ok` doesn't create the relevant tags.

There's no relevant entry in Browser Console at that time.

Also, pressing `Cancel` doesn't close the popup.
You have to press X to close it.

**Comment by jerone** [comment]
Some time ago the layout broke, and now the logic is broken too. When I have time I'll have a look at it. Any contribution is appreciated.

**Comment by mikhoul** [comment]
Same thing here, Image link don't work :disappointed:

**Comment by jerone** [comment]
Closing this issue as Github Comment Enhancer is deprecated.
