### ISSUE TITLE
New Outlook sign-in/login screen has "bypassed" Multiple Windows Live IDs

### ISSUE THREAD

**Issue by Grodge** [jerone/UserScripts#103]
Since 1st April 2016, the "new" Microsoft sign-in screen has completely bypassed the sign-in that was offered by Multiple Windows Live IDs. No personal settings/config offered by this script can be used, and only the Microsoft screen is seen. Would be very grateful for a fix.

**Comment by jerone** [comment]
People who can't wait and want to try the developer version, can follow and install from the working branch: https://github.com/jerone/UserScripts/compare/Multiple_Windows_Live_IDs

For now it only restores the tiles and logging-in by clicking. No edit/manage support just yet.

**Comment by jerone** [comment]
The new login should look something like:
![2016-04-15 17_31_42-sign in](https://cloud.githubusercontent.com/assets/55841/14566500/1c8c7c92-0330-11e6-9687-397a738a55cf.png)

**Comment by Grodge** [comment]
I installed the new script, and confirmed that version 0.1.2 was definitely installed. I found that the tiles still did not appear, and the new Outlook sign-on screen was all I saw (no change).

As a test - I then tried removing every GM script that I use, leaving only "Multiple Windows Live IDs" and I also removed every Addon that I use, leaving only Greasemonkey. I also updated Greasemonkey to the latest version. 

This leaves a very basic and "clean" Firefox (Portable), but I still see no tiles, and no changes - only the Outlook sign-on screen. Can you help? Can I try anything else you can suggest?  Many thanks.

**Comment by jerone** [comment]
Can you confirm that you installed the latest version from [this page](https://github.com/jerone/UserScripts/blob/Multiple_Windows_Live_IDs/Multiple_Windows_Live_IDs/Multiple_Windows_Live_IDs.user.js) by pressing the <kbd>raw</kbd> button.

Can you also open up Firefox's Browser Console and see if any errors appear (related to this script).

Third, can you confirm that your screen looks the same as the right part of above's screenshot?

Last can you confirm in the Web Console that the following code returns an actual element: `document.getElementById("maincontent");`

**Comment by Grodge** [comment]
Thank you. It is now working for me. I don't know why not the first time, as I checked carefully that the script was installed, and the old one removed. 

I found only two things: that my email tiles needed to be created again, and also the possibility of a small error, whereby the "first" tile duplicates itself if you make an edit upon it. In other words, any edit results in two of those "first" tiles. The remaining tiles did not manifest this error. No problem, as I just deleted one of those, and I mention this only if it can help.

It works again with the new Microsoft sign-in screen, and also with older GM version, and plays nicely with all my other scripts and Addons. All working great thanks.

**Comment by jerone** [comment]
> I found only two things

It's still work in progress. No edit/manage support just yet.

**Comment by jerone** [comment]
:clapper: Just updated this userscript to support adding/editing again.

**Comment by Grodge** [comment]
Thank you. 

The update to support adding/editing does seems to have removed "all existing tiles". Is that the behaviour you expect?  If yes, and now all fixed - I will recreate all tiles and then hope all will be good for some time....

**Comment by jerone** [comment]
> The update to support adding/editing does seems to have removed "all existing tiles". Is that the behaviour you expect?

If you previously uninstalled the script at one point, yes.

**Comment by Grodge** [comment]
Thank you.  Uninstalled at a previous (older) time yes....but not at the point of 'upgrade' - yet still all tiles were lost.

Perhaps to look at it another way, is there a location for the "user data" (the tiles), and is that user data separated from your code?  If "yes", then I can move that file to another machine, and always preserve my tile settings.  I only ask because I have quite a few (x7).  If not separated, no problem, I can remake.  Thanks.

**Comment by jerone** [comment]
GreaseMonkey handles all storage of settings. You can read about it here: https://wiki.greasespot.net/GM_setValue

**Comment by jerone** [comment]
New version is released. Let's hope Microsoft doesn't update their site anytime soon.

**Comment by Grodge** [comment]
Yes, you have put a lot of work into this truly excellent script, and I hope too - that Microsoft leave things alone for at least a couple of years. Many thanks! All working great.
