### ISSUE TITLE
Seem to be completly broken as of now !

### ISSUE THREAD

**Issue by mikhoul** [jerone/UserScripts#106]
Here's what I see: http://i.imgur.com/DKepRca.png

Regards :)

**Comment by jerone** [comment]
Which script?

**Comment by mikhoul** [comment]
Sorry , 
Github Comment Enhancer under Firefox (Win7) :smiley_cat:

**Comment by mzso** [comment]
Too bad. This was a neat script. I sorely miss the quote feature.

**Comment by mikhoul** [comment]
Seem abandoned sadly :disappointed:

**Comment by jerone** [comment]
After https://github.com/jerone/UserScripts/issues/98 it's hard to keep up with the changes from Github without any contributions. I'm not sure I want to keep updating GCE...

What I did was split the reply-functionality into separate userscript: https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments

**Comment by mzso** [comment]
[**@jerone**](https://github.com/jerone) commented on [2016. máj. 29. 15:12 CEST](https://github.com
> What I did was split the reply-functionality into separate userscript: [https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments](https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments)

Cool. That's what I missed most anyway.

**Comment by jerone** [comment]
Closing this issue as Github Comment Enhancer is deprecated.

**Comment by vanowm** [comment]
Deprecated because of different script available or because it's abandoned?

In either case would be nice if was stated at https://openuserjs.org/scripts/jerone/Github_Comment_Enhancer so we would not waste our time...
Thank you.

**Comment by jerone** [comment]
[**@vanowm**](https://github.com/vanowm) commented on [3 apr. 2017 14:24 CEST](https://github.com/jerone/UserScripts/issues/106#issuecomment-291127574 "2017-04-03T12:24:23Z - Replied by Github Reply Comments"):
> Deprecated because of different script available or because it's abandoned?
> 
> In either case would be nice if was stated at https://openuserjs.org/scripts/jerone/Github_Comment_Enhancer so we would not waste our time...
> Thank you.

Hi @vanowm, there's a deprecation message on the [repo home](https://github.com/jerone/UserScripts#readme) and twice on the [userscript readme](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer). GreaseFork has auto-sync, so it shows the [deprecation message there](https://greasyfork.org/en/scripts/493-github-comment-enhancer) too, but I guess [I have to do OUJS](https://openuserjs.org/scripts/jerone/Github_Comment_Enhancer) manually (which I just did). Sorry for your inconvenience.
