### ISSUE TITLE
GitHub Comment Enhancer RTL button

### ISSUE THREAD

**Issue by Mottie** [jerone/UserScripts#110]
I found [this issue](https://github.com/dear-github/dear-github/issues/147) about GitHub not supporting right-to-left languages. I found that text wrapped in a paragraph tag with RTL attributes works!

<p dir='rtl' align='right'>RTL language</p>

```html
<p dir='rtl' align='right'>RTL language</p>
```

I think this addition would be perfect for your GitHub Comment Enhancer script!

**Comment by jerone** [comment]
Interesting feature. But since https://github.com/jerone/UserScripts/issues/106 GCE is broken and I wouldn't expect new features to be implemented.

**Comment by Mottie** [comment]
Oh yeah, nothing is accessible from the console anymore (including jQuery) :disappointed:

**Comment by Mottie** [comment]
So I ended up writing my own userscript... darn OCD :stuck_out_tongue: 

https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-rtl-comments

**Comment by jerone** [comment]
Good work :+1:
