### ISSUE TITLE
Github Commit Diff - Viewing file as .patch broken

### ISSUE THREAD

**Issue by zonkmachine** [jerone/UserScripts#119]
Script: Github Commit Diff 1.6.5
Browser: Firefox 54.0(64-bit), Mozilla Firefox for Linux Mint
Addon: Greasemonkey 3.11
Error Message: -
Description: Viewing file as .patch with shift key option broken. With Firefox option to open new page as tab activated the .diff is opened as a new window instead.

**Comment by jerone** [comment]
Thanks! I've confirmed it and fixed. An update should be available soon.

**Comment by zonkmachine** [comment]
Fix confirmed. Thanks!
