### ISSUE TITLE
(GitHub News Feed Filter) The addition of the tab 'Discover repositories' in the News Feed has broken the script functionality

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#121]
Using FF 56.0.1 (tested in a clean profile too) with GM 3.17 and script v7.2.0.

Yesterday, an extra tab, 'Discover repositories' was added in the News Feed ([blog post](https://github.com/blog/2447-a-more-connected-universe)).
Unfortunately, this has broken the script functionality:
- all counters in the 'News feed filter' table now have zero values, and, 
- clicking any filter entry, no filtering is applied to the news feed.

_There's no entry in Browser Console when this happens._

<br>

@jerone, it would be great if you fixed the script, to work with the new layout. I love your script!

**Comment by jerone** [comment]
Yeah, just got the new layout too. Already working on it, but it's not a simple replace classnames. They completely rewrote all news alerts. I hope to finish it this weekend.

**Comment by jerone** [comment]
@darkred Do you have any issue related news items in your news list?

**Comment by darkred** [comment]
No, I haven't. any..
It must be a GitHub bug: I got an email notification for a new issue in the Greasemonkey repo (2616),
but it doesn't appear in the news feed.

**Comment by jerone** [comment]
Me neither. No issues and PR related news (and gist, but that could be because there isn't any in my feed). Also wondering if it's temporary or by design...

**Comment by jerone** [comment]
I also remembered news items about members being added to repos. Those are gone too.

**Comment by jerone** [comment]
I just pushed code changes that (hopefully) restores  a working version of this userscript. I've not updated version numbering, because I was wondering if you have time to [test it](https://github.com/jerone/UserScripts/tree/master/Github_News_Feed_Filter#readme) before releasing...

**Comment by darkred** [comment]
Of course. 
It's working great, again. Thank you!

I also contacted the GitHub support about the missing entries in the News Feed.  
I'll let you know, as soon as I get a reply from them.

**Comment by darkred** [comment]
Unfortuntately it's a feature.. 
Here is the response:

> What you're seeing is not a bug, but instead is the result of some updates we've made to our news feed. The updated feed focuses on helping users find open source repositories that line up with their interests, which you'll see in the new Discover repositories.
>
>The Browse activity tab has also been streamlined, and certain events, such as Pull Requests and Issue comments, are no longer included. You can still see these events if you check your notifications page.
>
> We're very interested in any feedback users like yourself have on these changes, so do please let us know what these changes will mean for how you use GitHub. It sounds like these changes may not be ones you consider an improvement, but any comments we receive will be included in our ongoing conversations about how to improve GitHub.

And my reply: (at least I tried!)

> Unfortunately I don't find practical the removal of these entries from the News Feed - in fact I find it confusing to have only some of them in the News Feed, and the rest in Notifications.
> I find issue entries equally important as the other entry types, because a posted issue could affect me as a user too, and the News Feed is the quickest way to notice it.
> And PRs as well: it's good to get informed of the suggested contributions in the various repos that I watch, as they are submitted - not after getting merged.
> 
> Frankly, instead of moving these entry types from the News Feed to Notifications,
I'd suggest adding them back, and just incorporate this excellent userscript https://github.com/jerone/UserScripts/tree/master/Github_News_Feed_Filter ,
which makes filtering (by Action Type, Repository and/or Users, i.e. you may apply filters from all these 3 filter categories, simultaneously) a breeze!

**Comment by darkred** [comment]
One thing I noticed in the userscript, (I post it here)
is that in the 'Users' tab, the usernames are currently sorted alphabetically. 
I find this confusing as I visually compare them with the displayed entries in the News Feed.
So, would you like please to display the usernames in the order they appear in the News Feed (like it's done in the 'Repositories' tab? I find it's more practical this way.

**Comment by jerone** [comment]
I don't expect them to restore it, so those (and Member Add and Gists) are removed for now (we can always revert the commit).

**Comment by jerone** [comment]
I just released the new version of Github News Feed Filter 🎬

I've not confirmed that every filter is working (because they weren't in my news feed), so if you see anything not working let me know. The total amount of filters should always be a factor of 30.

Thanks for helping with testing 🥇
