### ISSUE TITLE
Reply Comments works on GreaseMonkey too

### ISSUE THREAD

**Issue by aspiers** [jerone/UserScripts#122]
Thanks a lot for all these!  Reply Comments works great for me on GreaseMonkey on Chrome too, so maybe you want to add this to the README?

**Comment by aspiers** [comment]
Ah, just noticed that you have all userscripts in one repo - editing issue accordingly...

**Comment by jerone** [comment]
Thanks for mentioning (aldo i thought GM was only for Firefox) 🙂

I won't add it to the list because that means I support it officially, but i try to make (most of) my scripts browser and (web)extension independent.

**Comment by aspiers** [comment]
Thanks for the reply. Well, you could update the README to say that it has been known to work for some people on Chrome but it's unsupported and their mileage may vary, caveat emptor etc. That way at least they would instantly know that it's not necessarily a waste of their time to try it out on Chrome.
