### ISSUE TITLE
(GitHub News Feed Filter) The 'Repositories' tab is empty. Also please consider displaying the filter's entries by default, as it was in previous versions

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#124]
Using GNFF 8.1.0 with Tampermonkey 4.6 in Chrome 66/Firefox 60 (tested in a new profile too).

I've noticed that whenever I click the 'Repositories' tab, it's empty of content. 

This is an example error entry from the Chrome's console:
```
ERROR: Execution of script 'Github News Feed Filter' failed! Failed to execute 'add' on 'DOMTokenList': The token provided ('5 repositories') contains HTML space characters, which are not valid in tokens.
```
and here from Firefox's console:
```
ERROR: Execution of script 'Github News Feed Filter' failed! String contains an invalid character                userscript.html:2:172
```

---

_<strike>Also, as a sidenote, I'd like to ask you please to consider displaying the filter's entries by default, as it was in previous versions of the script.
Currently you have to click either the 'Actions' or the 'Repositories' title, for its content to populate. I would definitely prefer the previous behavior.
Maybe, also make it so that a second click on any of the titles (Actions/Repositories/'News feed filter')  to cause the filters content to collapse. And if there's a filter remains active, to make the parent title (Actions/Repositories)  bold, as a visual reminder.</strike>_

----

<br/>
Thank you

**Comment by jerone** [comment]
Hi @darkred, I'm actually not using this userscript anymore as it's not compatible with [Refined GitHub extension](https://github.com/sindresorhus/refined-github). I do accept a PR, if you are willing to fix the issue.

**Comment by darkred** [comment]
> I do accept a PR, if you are willing to fix the issue.

Of course, here: https://github.com/jerone/UserScripts/pull/126

_I love your script, it's one of my most favorites for GitHub!_ 👍 


PS. I have also installed the Refined GitHub extension but unfortunately it conflicts with some of the (great) GitHub scripts by Mottie and haven't looked into it yet, so I keep it disabled.

**Comment by darkred** [comment]
Hey @jerone 

First of all, I was informed <sup>[1]</sup> that if I add `hide-useless-newsfeed-events` in Refined GitHub's Options|'features to disable'
then no entries in dashboard are hidden by the extension anymore,
i.e. there's no conflict with your script anymore.

Also, after the recent GitHub layout update (repos and teams on the left with activity on the right, including issues you've commented on with recent activity, being on top).
the script stopped working again, and that's irrelevant to GitHub Refined.

By making the modifications below, I managed to make your script partially work again, i.e. at least to execute without errors.

<br/>

I'm telling you all this, mostly in case you hadn't tried 'hide-useless-newsfeed-events',
that would change your mind about start using your script again,
and if yes, whether you would like to take a look in fixing the 3 remaining issues listed in the end (they are caused by the recent GitHub update - they are irrelevant to GitHub Refined).

I've tried to fix these issues myself, but unfortunately it's proven too advanced for me so far..


---

## The modification

By changing in line 275 'protip' to e.g. 'protip2':

```
none.classList.add('no-alerts', 'protip2');
```

and in line 277 the selector from '.tabnav' into '.js-details-container':

```
newsContainer.insertBefore(none, newsContainer.querySelector('.js-details-container').nextElementSibling);
```

i.e. the script executes without errors again,
and the 'No feed items for this filter. Please select another filter.' for non-matching filters is displayed ok again.

---

## The three issues left:
- The global counters 'All news feed'. 'All repositories' and 'All users'
all get the same (wrong) value of 'All news feed', e.g. `38 (38)`. 
Also, the 'Actions' tab|Commits counters, and the 'Repositories' tab counters values are all wrong.
- The: 'Actions' tab|'User' filter always shows '0' (lists no usernames).
- The 'Users' tab is empty (lists no usernames).

[1] `https://github.com/sindresorhus/refined-github/issues/1336#issuecomment-390321708`

**Comment by darkred** [comment]
Yes, they all happen, even in a fresh Chrome 66/Firefox 60 profile with only latest Refined GitHub 18.5.19.1605 (with `hide-useless-newsfeed-events`), Tampermonkey 4.6 and your script. 8.1.1

For reference, here is a current screenshot of my dashboard (it's a long/scrolling screenshot)
[2018-05-20_123103](https://user-images.githubusercontent.com/723651/40277580-cf59ef9a-5c29-11e8-9a15-bcf8a75b4379.jpg)


Now, please notice in my 1st capture below: 
- as I switch tabs, the 'Actions' tab|'All news feed' counter and the 'Repositories' tab|'All repositories' are both wrongly 38. In 'Users' tab|Users, the counter is 0. 
- the counter of 'Actions' tab|'Commits' is wrong: it's not 7 (that's just the value of the 1st entry), it's actually 7+2+1+... (2nd capture) <--- and it immediately changes wrongly to 15 
- the 'Actions' tab|'User', the 'Actions' tab|'Wiki' and the 'Users' tab are all wrongly empty.

<details>
<summary>Capture1:</summary>

![](https://user-images.githubusercontent.com/723651/40277699-61de0c78-5c2c-11e8-9b5b-3de3b38984d2.gif)
</details>

<details>
<summary>Capture2:</summary>

![](https://user-images.githubusercontent.com/723651/40277774-5a61a03a-5c2d-11e8-8fc2-a71bc37a5037.gif)</details>

**Comment by darkred** [comment]
Correction: the counter of 'Actions' tab|'Commits' works ok, I wrongly thought it counts commits, not groups of commits. Sorry about that.

**Comment by jerone** [comment]
Just pushed an update, which I hope will fix all your issues (for me it does)!

I say I hope, because I don't have those 4 pinned issues at the top like you have, so I can't test that.

**Comment by darkred** [comment]
Thank you very much !!! I really appreciate your help! Great 👍 

I also made PR #127 to fix the 'Actions' tab|'Wiki' being empty. 🙂

**Comment by darkred** [comment]
And, one last thing:

there were some entries still missing in 'Repositories' tab|All repositories:

in the screenshot below, if you do the sum, it's 27, not 30:
![2018-05-20_155415](https://user-images.githubusercontent.com/723651/40279147-12624b90-5c46-11e8-9f4c-55b72e21b372.jpg)


The fault was the change I had made in the my initial PR for the selector in the alertRepo variable:
I restored the selector as you had them before in my PR.
