### ISSUE TITLE
(GitHub Reply Comments) doesn't work with PR review comments

### ISSUE THREAD

**Issue by aspiers** [jerone/UserScripts#125]
When comments are made as part of a PR review, the reply button doesn't appear for any of those comments, e.g.:

- https://github.com/aspiers/test/pull/5
- https://github.com/aspiers/test/pull/5/files

**Comment by jerone** [comment]
Thanks for those test-cases. I can confirm the review reply button being abset.

**Comment by jerone** [comment]
Fixed and released 🎉
