### ISSUE TITLE
(GitHub News Feed Filter) The script's tab titles (Actions, Repositories, Users) appear tiled vertically after today's GitHub site update

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#130]
Using GNFF 8.2.2 with Tampermonkey 4.6 in Chrome 66/Firefox 60 (tested in a new profile too).

The issue is that the script's tab titles (Actions, Repositories, Users) appear tiled vertically after today's GitHub site update (i.e. [the updated search bar](https://twitter.com/github/status/999706528373493766) I think)

Here is a screenshot from FF:
![2018-05-24_193749](https://user-images.githubusercontent.com/723651/40504369-bdf5d232-5f99-11e8-95ff-3ab83403d253.jpg)

There's no error in Browser Console.
Unfortunately I couldn't find how to fix this.

**Comment by jerone** [comment]
Yeah, they removed the required CSS for tab styling. Didn't have time to look for a better replacement. Will look next week. Luckily everything still works.

**Comment by jerone** [comment]
@darkred If you wanna have a go at this issue, go for it :)
