### ISSUE TITLE
(Github Reply Comments) Doesn't work on commit view

### ISSUE THREAD

**Issue by aspiers** [jerone/UserScripts#133]
Github Reply Comments doesn't work on commit view, e.g. visit a page like:

https://github.com/openSUSE/osc/commit/ae591a82fc0678c

and then clicking the Reply button will result in the following JS error on the browser console:

    Uncaught TypeError: Cannot read property 'classList' of null
        at getCommentTextarea (userscript.html?id=1…2c-d2362a319eb3:224)
        at HTMLButtonElement.eval (userscript.html?id=1…2c-d2362a319eb3:259)
    getCommentTextarea	 @ userscript.html?id=1…2c-d2362a319eb3:224
    (anonymous)              @ userscript.html?id=1…2c-d2362a319eb3:259

**Comment by jerone** [comment]
Thanks. I can confirm the issue, just need some time to find a fix.

**Comment by jerone** [comment]
FYI, i have a fix for this, am testing it now. Will try to push an update this week.

**Comment by jerone** [comment]
@aspiers This should be fixed by now.

**Comment by aspiers** [comment]
Works great now, thanks so much!
