### ISSUE TITLE
UTF8 byte-order-mark at beginning of files

### ISSUE THREAD

**Issue by The-Compiler** [jerone/UserScripts#135]
At least [Github_Pull_Request_From.user.js](https://raw.githubusercontent.com/jerone/UserScripts/master/Github_Pull_Request_From/Github_Pull_Request_From.user.js) (but probably others as well) does have a [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark).

This does violate what's documented in the [Greasemonkey wiki](https://wiki.greasespot.net/Metadata_block):

> Note that the opening `// ==UserScript==` and closing `// ==/UserScript==` must be precisely at the beginning of its line. 

since the file starts with `0xEF, 0xBB, 0xBF` before the `// ==UserScript==`.

This causes it to not work properly in [qutebrowser](https://www.qutebrowser.org/). I'll fix this there as well (by stripping it), but it might affect other Greasemonkey implementations as well.

Assuming you're on Unix, you should be able to remove them all using:

```
$ find . -name '*.js' -exec sed -i $'1s/^\uFEFF//' {} \;
```

Alternatively (if your editor inserts them), I guess it'd be possible to move the `// ==UserScript==` line to the second line.

**Comment by jerone** [comment]
Hi @The-Compiler, all my userscripts are compatible with Tampermonkey, where the UTF-8 BOM appears no issue. But I'm happy to accept (most) PR to support other userscript clients.
