### ISSUE TITLE
(GitHub News Feed Filter) The script sometimes doesn't work when navigating from other GitHub pages to the news feed

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#137]
Using Chrome 69 in win10, TM 4.8.5850 beta, and only GitHub News Feed Filter 8.2.4.

The issue is that some times when navigating to https://github.com/ from other GitHub pages the script doesn't work: in such cases I have to press Ctrl+F5 in order to work (plain F5 doesn't help).

STR
- Open https://github.com/ in a new tab: notice that the script works ok,
- Now click the "Explore" link (`https://github.com/explore`)
- Now click the Github logo icon to the upper left corner to navigate back to https://github.com/ : 
notice that the script doesn't work (there's no error in Console). Pressing Ctrl+F5 fixes the issue.

FWIW I've tried adding `// @include     https://github.com/*` but unfortunately it didn't help.

**Comment by jerone** [comment]
Hi @darkred. Currently I'm [beta testing](https://help.github.com/articles/opting-into-the-public-beta-for-a-new-dashboard/) the [new personal dashboard](https://help.github.com/articles/about-your-personal-dashboard/) on the homepage. This will replace the current news feed on the homepage. That's why I'm not using this userscript anymore and probably won't make any updates to the userscript until GitHub releases the new dashboard or disables the beta. 

I have not checked the source yet, but this userscript might still be relevant on the new dashboard.

PR is always welcome!

**Comment by darkred** [comment]
Hi @jerone. 

Yes, I'm also using the new dashboard layout, too.
And yes, the script still works fine on the new dashboard: [screenshot](https://user-images.githubusercontent.com/723651/46009008-f918a680-c0c6-11e8-9db8-d661a098cb5e.jpg).
It's just this issue that I describe occurs.

FYI, apart from adding 
```
// @include       https://github.com/*
```
I've also tried enclosing your code as follows, like I've done with the [GitHub script](https://github.com/darkred/Userscripts/blob/master/GitHub_Confirmations_before_submitting_issues_and_comments/GitHub_Confirmations_before_submitting_issues_and_comments.user.js) I have, 
but unfortunately it didn't help:

```javascript
(function () {
	function init() {

	// ...
	
	}
	init();
	document.addEventListener('pjax:end', init); // for the History API
})();
```

---

Kindly /cc @Mottie in case he'd like to help here - I think his `mutations.js` library 
(and the [HowTo](https://github.com/Mottie/GitHub-userscripts/wiki/How-to) he also provides ) would be the best solution to this.

**Comment by jerone** [comment]
> Yes, I'm also using the new dashboard layout, too.

Hmmm, that's weird, are you sure? Because I couldn't even get the filter to show up on the new dashboard.

To make the filter show up, change the following line...
```js
sidebar.insertBefore(wrapper, sidebar.firstChild);
```
...to...
```js
sidebar.insertBefore(wrapper, sidebar.querySelector(":scope > *:not(details)"));
```

It appears that all features still work.

I also can't reproduce the issue you are describing, with above steps. 😞

**Comment by darkred** [comment]
> Hmmm, that's weird, are you sure? Because I couldn't even get the filter to show up on the new dashboard.

Yes, of course.
The previous screenshot I gave you is from a fresh Firefox 62 profile with only TM and the script:
> [screenshot](https://user-images.githubusercontent.com/723651/46009008-f918a680-c0c6-11e8-9db8-d661a098cb5e.jpg)
Here is a screenshot from Chrome 69, with TM being the only extension enabled, and the script:
[2018-09-26_000736](https://user-images.githubusercontent.com/723651/46043260-3e1cf700-c120-11e8-86cf-7e85caf747ec.jpg)

Notice the "You are in the public Beta of the dashboard" text to the bottom left of both screenshots.

In both cases the script is as it (8.2.4), i.e. without your suggested modification to line 498.

<br/>

The issue that I describe is occurring frequently but not every single time, i.e. not consistently.

Here is a video (01:16, ~5 MB) with Chrome 69 and TM 4.8.5850 stable  *(the same thing happens with Firefox and Tampermonkey beta)* :  [Video_2018-09-26_001858.zip](https://github.com/jerone/UserScripts/files/2417139/Video_2018-09-26_001858.zip) <sup>[1]</sup> : 
while I'm https://github.com/
and click in terms the links: "Pull Requests", "Issues", "Marketplace", "Explore" and (my avatar) > 'Your Profile'", and every time I switch back to https://github.com/ : 
the issue I describe occurs at: 0:27 (one time) and 01:05 (twice) of the video, i.e. 3 times in total.

<sup>[1]</sup> Please download and unzip it - unfortunately uploading .WMV files is not supported by GitHub. Sorry for the inconvenience.

**Comment by darkred** [comment]
(I've made some corrections to my last comment to improve the wording).

**Comment by jerone** [comment]
When I have time I'll have a look.

One thing I did notice between you and me is the difference on the left sidebar; I've got an account switcher, which you doesn't seem to have...
![image](https://user-images.githubusercontent.com/55841/46065031-510be780-c171-11e8-85b9-4d08e3321c57.png)
_(I have Refined GitHub 18.9.19.1710 disabled at the moment I made the screenshot)._

**Comment by darkred** [comment]
> When I have time I'll have a look.

Thank you! 🙂 

> One thing I did notice between you and me is the difference on the left sidebar; I've got an account switcher, which you doesn't seem to have...

Yes, that's very strange. I also use Refined GitHub (as well as Octotree, OctoLinker, Octobox and various styles for Stylus) but I have these extensions disabled during the above tests, and I don't have such an account switch in any case, with any browser (Chrome, FF, even Edge).

**Comment by jerone** [comment]
It's because I'm part of a few organizations: https://github.com/jerone

Not related to your real issue, but if you make the code change [I described above](https://github.com/jerone/UserScripts/issues/137#issuecomment-424493379), does the news-feed-filter still show-up for you?

**Comment by darkred** [comment]
Yes, unfortunately it still shows up.

**Comment by jerone** [comment]
> Yes, unfortunately it still shows up.

No no, that's good news 😄  that means that this change will make the news-feed-filter show on accounts with and without organizations.

Now I only need to reproduce your issue... 😞

**Comment by darkred** [comment]
> No no, that's good news 😄 
Yes, sorry, I misread it as "Does the issue still occur?" 😄

**Comment by darkred** [comment]
> I'll confirm that it works at home also, can you confirm if the news-feed-filter still is shown for you too...

Yes the news-feed-filter is still shown for me.
And also, with these two changes combined, the issue no longer occurs: I've tried multiple (a lot) times and I can't recreate it anymore 👍

**Comment by darkred** [comment]
Something that got my attention: I noticed [in your screenshot](https://user-images.githubusercontent.com/55841/46065031-510be780-c171-11e8-85b9-4d08e3321c57.png)
that there's a blue counter badge (`1`) over the unread notifications icon:
![46065031-510be780-c171-11e8-85b9-4d08e3321c57](https://user-images.githubusercontent.com/723651/46096986-5432c200-c1c9-11e8-8196-919d0e5fb8bb.png)

What extension/userscript do you use for that feature?

**Comment by jerone** [comment]
> Yes the news-feed-filter is still shown for me.

Great. 😄 

>  And also, with these two line changes combined, **the issue no longer occurs**: I've tried multiple (a lot) times and I can't recreate it anymore 👍

Even greater. 😆 

> What extension/userscript do you use for that feature?

I used [some](https://github.com/SkyzohKey/GitHub-Dropdown-Notifications) UserScript before, but then I found the more frequently updated WebExtension, [Notifications Preview for GitHub Build Status](https://github.com/tanmayrajani/notifications-preview-github).


I'll release a new version of the the script soon.

**Comment by jerone** [comment]
Finally had some time to push the fix. I hope everything continues to work. 😄

**Comment by darkred** [comment]
Yes, everything is fine, thank you 👍
