### ISSUE TITLE
(Github Pull Request From Link) Wrong url on forks where another repo name is choosen

### ISSUE THREAD

**Issue by eight04** [jerone/UserScripts#145]
Script: Github Pull Request From Link 19.1
Browser: Cent Browser Version 3.8.5.69 (Official Build) (32-bit) (Chromium 71.0.3578.98)
Addon (e.g. Tampermonkey): Tampermonkey BETA 4.8.5898
Description:

STR:

1. Visit https://github.com/stylus/stylus/pull/2416
2. Click the `eight04:dev-empty-at-rules` link
3. Navigate to https://github.com/eight04/stylus/tree/dev-empty-at-rules and result as 404.

It seems that the repo name in `title` attribute is correct.

**Comment by jerone** [comment]
Thanks for reporting. 
I can confirm this being an issue. 
It looks like [GitHub Refined](https://github.com/sindresorhus/refined-github/) is doing [it correctly](https://github.com/sindresorhus/refined-github/blob/master/source/features/linkify-branch-refs.tsx). 
I'll investigate.

**Comment by jerone** [comment]
It looks like you choose another name than the original repo name; `stylus-1` instead of `stylus`: `https://github.com/eight04/stylus-1/tree/dev-empty-at-rules`.

Anyways, this is [fixed](https://github.com/jerone/UserScripts/tree/master/Github_Pull_Request_From#readme).
