### ISSUE TITLE
Is this fully broken now? Some features I miss.

### ISSUE THREAD

**Issue by mzso** [jerone/UserScripts#147]
Hi!

Features such as strike-through, underlined, and some others I occasionally miss.
They're not presen on the built in buttonbar. Are they even still possible via formatting?

I noticed the deprecation warning. (But also an update of sorts recently)

**Comment by jerone** [comment]
In this repo are [many UserScripts](https://github.com/jerone/UserScripts#readme), but I guess you are talking about [Github Comment Enhancer](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer#readme).

And yes, Github Comment Enhancer is **still deprecated**. The [commit](https://github.com/jerone/UserScripts/commit/bb7e2ed6e587f88512ecf222fb9eb7b212da9624) was only about the UserScript icon being broken. I skipped increasing the version for this script.
