### ISSUE TITLE
Seems like the reply script got broken recently

### ISSUE THREAD

**Issue by mzso** [jerone/UserScripts#149]
Nothing is added to the text field when I click on the reply icon.

**Comment by jerone** [comment]
[**@mzso**](https://github.com/mzso) commented on [Nov 4, 2019, 1:11 PM GMT+1](https://github.com/jerone/UserScripts/issues/149#issue-517112641 "2019-11-04T12:11:57Z - Replied by Github Reply Comments"):
> Nothing is added to the text field when I click on the reply icon.

Thanks for mentioning. I noticed it too, but hadn't confirmed it yet. Anyways... it's fixed. Installation [via GitHub](https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments#readme) will update quickly, [other services](https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments#external-links) will update soon.
