### ISSUE TITLE
Breaks with GitHub usernames containing spaces

### ISSUE THREAD

**Issue by aspiers** [jerone/UserScripts#150]
e.g. look at the edits I had to make to [this comment](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-559452467).

**Comment by jerone** [comment]
Confirmed and thanks. Will release a fix tonight.

**Comment by jerone** [comment]
GitHub Refined did add something similar recently: https://github.com/sindresorhus/refined-github/pull/2556. They only include the username.

The main advantage of this UserScript is that the whole message is pinned by the current time. This is useful when replying to an users message, and they edit the message after replying.
