### ISSUE TITLE
(Reply Comments) Doesn't enable the Comment button

### ISSUE THREAD

**Issue by aspiers** [jerone/UserScripts#152]
After clicking the "Reply to this comment" button, the comment textarea field populates correctly, but the big green "Comment" submission button beneath it remains greyed out, so it's impossible to submit the comment.  This seems like a fundamental breakage of the functionality of this userscript.

A workaround is `Control+A Control+X Control+V` to cut and re-paste the whole text, but this is pretty annoying.

**Comment by jerone** [comment]
Hi @aspiers, did you enable the preview features "Repository refresh" and/or "Design updates" (or others)?

**Comment by aspiers** [comment]
No I don't think so - in fact, I don't see those settings; where are they?

**Comment by jerone** [comment]
![](https://user-images.githubusercontent.com/55841/85145401-ce806100-b24c-11ea-8f7a-fc18a03a19bb.png)

**Comment by jerone** [comment]
I'll have a look at why it's broken later. Any other extension that might be important (Refined GitHub for example)?

**Comment by aspiers** [comment]
I tried disabling all other userscripts and GitHub extensions, and still saw the problem.  Enabling the preview features didn't change it either.

**Comment by jerone** [comment]
@aspiers Sorry it took so long to fix. New version released.

**Comment by aspiers** [comment]
Amazing, thanks!
