### ISSUE TITLE
Github Pages Linker no longer works

### ISSUE THREAD

**Issue by leocaseiro** [jerone/UserScripts#158]
I think Github updated its UI and components. So the script no longer works.

**Comment by darkred** [comment]
@leocaseiro 
Your version unfortunately has a side effect:
it causes clicks on the branch selector, so it's expanded and then closed momentarily.

STR

Just open any repo page, e.g. [this repo](https://github.com/jerone/UserScripts/) having login to GitHub or not,
and notice the branch selector element:
![12345~](https://user-images.githubusercontent.com/723651/120357282-ef32b100-c30d-11eb-95f4-b3ad7de57e56.gif)

Tested with latest Tampermonkey 4.13.6137 beta with Chrome 91, Firefox 89  (fresh profiles)

**Comment by jerone** [comment]
Oh lol, that's why I was seeing that. Will have a look at it.

**Comment by jerone** [comment]
So, I just released a new version. But there are some limitations:

1.  It's slow and heavy.
2.  It only works on the root of the project page.

Open for other PR's to improve ux...

**Comment by leocaseiro** [comment]
Yeah, it's a little junky, and it's getting annoying, I'll try to improve that when I have some more time.

**Comment by leocaseiro** [comment]
Oh, just noticed you did fix it with the `environments`. Good job @jerone 👏 
I think I can handle only using on the main page.
