### ISSUE TITLE
Confusing licensing

### ISSUE THREAD

**Issue by SamB** [jerone/UserScripts#163]
A lot (all?) of these scripts have the metadata:

```
// @license     CC-BY-NC-SA-4.0; https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
// @license     GPL-3.0-or-later; http://www.gnu.org/licenses/gpl-3.0.txt
```

Unfortunately, there doesn't appear to be an established meaning for multiple `@license` keys.

GreasyFork documents the key at <https://greasyfork.org/en/help/meta-keys#meta-license>, but doesn't support multiple instances of the key ([gf_code][]), so naturally they also don't talk about what that might mean.

OpenUserJS doesn't have any obvious documentation for the key at all, but I chanced upon a link to 
<https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#license> from <https://github.com/OpenUserJS/OpenUserJS.org/issues/438> and ... oh dear, I just discovered their description on <https://openuserjs.org/user/add/scripts> and they describe the exact construct above as equivalent to the SPDX expression `(GPL-3.0-or-later AND CC-BY-NC-SA-4.0)` which ... well, those licenses are very much incompatible, so their conjunction is impossible to satisfy 😿.

[gf_code]: <https://github.com/JasonBarnabe/greasyfork/blob/b6ae7fb3d8017660ee7ba87d170ea732f0b4ed5e/app/models/script.rb#L295>

**Comment by jerone** [comment]
Hi @SamB. I'm not sure what your question is...

**Comment by jerone** [comment]
Anyways, CC-BY-NC-SA-4.0 and GPL-3.0-or-later are compatible.

See more info here: https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/
