### ISSUE TITLE
v1.0.5 Broken by 2023-11

### ISSUE THREAD

**Issue by mzso** [jerone/UserScripts#168]
Hi!

This seems to have broken recently. The reply button is unresponsive. And I think it was missing for some issues.

**Comment by jerone** [comment]
Hi @mzso, which script are you talking about?

**Comment by mzso** [comment]
Github Reply Comments. There's no insertion of quotes, nor scrolling to the input field.

**Comment by mzso** [comment]
@jerone 
So, will you take a look at it?

**Comment by jerone** [comment]
@mzso I'm not using it actively. But I'm open for a PR.

**Comment by Californ1a** [comment]
Looks like it's just one selector that needs to be changed:

https://github.com/jerone/UserScripts/blob/54e67737776a30fe40816f7d339da89722cd272e/Github_Reply_Comments/Github_Reply_Comments.user.js#L53

It seems like `.comment-form-textarea` doesn't exist on the new comment textarea anymore. No idea about the two other classes referenced in that selector.

**Comment by jerone** [comment]
@mzso A new version with a fix has been published.
