### ISSUE TITLE
(Twitter profile retweets hider) Only works for the currently visible tweets (it doesn't work as you scroll down the profile page -infinite scrolling-)

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#36]
The script no longer hides retweets in profiles.
I use Firefox 33.1.1 with GM 2.3 and v2 of the script.

That's what appears in Browser Console (if it's relevant):
> unsafeWindow.$ is not a function Twitter_profile_retweets_hider.user.js:117

**Comment by darkred** [comment]
I just tried your script in Scriptish (both [latest stable 0.1.12](https://addons.mozilla.org/en-US/firefox/addon/scriptish/versions/0.1.12) and [nightly  2014-11-20](https://github.com/scriptish/scriptish-nightlies/releases)) and it doesn't work.
The same error is shown in Browser Console:
`ReferenceError : unsafeWindow is not defined     twitterprofi: ...117`

**Comment by jerone** [comment]
I'm open for a PR. Otherwise I'll probably deprecate both Twitter scripts as I have no use for both scripts.

**Comment by darkred** [comment]
I've tried a lot (with my limited javascript knowledge) to properly convert the forementioned line,
but without any success.

**Comment by darkred** [comment]
Just tried the script again, and it's working ok now (using FF38.0.5 with GM 3.2).
`TypeError    unsafeWindow.$ is not a function     Twitter_pr:17` still appears though (just 1 entry) in browser console as a profile page is loaded,
but the script works ok, and there are no other error messages in browser console 
(neither as you scroll down the profile page nor as you toggle the script on/off).

**Comment by darkred** [comment]
To sum it up (currently using FF38.0.5 with GM 3.2) :
`TypeError    unsafeWindow.$ is not a function     Twitter_pr:17` appears (1 time) in browser console as a profile page is loaded.
When you toggle "Hide Retweets", the script works only for the currently viisible tweets, 
**But, it doesn't work as you scroll down the profile page (infinite scrolling).**

**Comment by darkred** [comment]
The script works ok now (using FF38.0.5 with GM 3.2).
