### ISSUE TITLE
(Github Comment Enhancer) Emulate tab as a button or snippet

### ISSUE THREAD

**Issue by r-a-y** [jerone/UserScripts#41]
Hi jerone,

Great userscript!  Was wondering if you could add a button or a snippet to emulate a tab keyboard press.  I usually end up using tabs instead of spaces to add indents in textareas.

I could add a pull request.  Just let me know what you prefer first.

Thanks for considering!

**Comment by jerone** [comment]
Interesting idea. Would be a good item for in the snippets list. :+1: 
I probably won't have the time to implement this myself, so a PR would be great.

**Comment by jerone** [comment]
Fixed by #42
