### ISSUE TITLE
(Github Comment Enhancer) Custom snippets

### ISSUE THREAD

**Issue by bb010g** [jerone/UserScripts#62]
Being able to add and use custom snippets would be nice.

**Comment by jerone** [comment]
You probably mean a way to add them without editing the `.user.js` file. I don't have any plans to add a whole UI for adding custom snippets. What snippets did had in mind of adding? If useful, I'll consider adding them.

If you want you can edit the userscript yourself and add new snippets by adding a function [here](https://github.com/jerone/UserScripts/blob/master/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js#L197-L211) and some HTML [here](https://github.com/jerone/UserScripts/blob/master/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js#L327-L338). _Note that with editing the userscript you lose automatic updates._

You're always free to sent a PR :smile:

**Comment by collegeimprovements** [comment]
It would be great if we can add custom snippets.
May be useful snippets: system info and version of related software: e.g. `node version 0.12.5` and computer info like `Mac 64 bit`

**Comment by jerone** [comment]
[**@collegeimprovements**](https://github.com/collegeimprovements) commented on [1 jul. 2015 02:38 CEST](https://github.com/jerone/UserScripts/issues/62#issuecomment-117379080 "2015-07-01T00:38:18Z - Replied by Github Comment Enhancer"):
> It would be great if we can add custom snippets.
> May be useful snippets: system info and version of related software: e.g. `node version 0.12.5` and computer info like `Mac 64 bit`  etc.

Getting information like node version and more are just not possible within userscripts. I'm bound to what Firefox and GM provide on information, which is currently only the useragent string.
Like I said above, you can edit the userscript yourself and add new snippets by adding a function [here](https://github.com/jerone/UserScripts/blob/master/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js#L197-L211) and some HTML [here](https://github.com/jerone/UserScripts/blob/master/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js#L327-L338). _Note that with editing the userscript you lose automatic updates._

**Comment by SkyzohKeyx** [comment]
Would be cool to be able to do that !
If I have a little time i'll try to make this and provide a nice UI to manage snippets ;)

**Comment by jerone** [comment]
Closing this issue as Github Comment Enhancer is deprecated.
