### ISSUE TITLE
(Github News Feed Filter) all entries counters are zero

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#68]
Today I noticed that entries counters (and sub-counters) are all zero: 
![screenshot](http://i.imgur.com/FP7ifAa.jpg)
Filtering still works ok.

This is what I get this in Browser Console when opening https://github.com/ :

```
alert.querySelector(...) is null             Github_News_Feed_Filter.user.js:210:8
```

Using FF40(tested in a clean profile too) with GM 3.3 and script v5.3.

**Comment by jerone** [comment]
Hmm, just tested and can't confirm with same specs. The script works for me just as intended. Do you have any other userscripts running?

**Comment by darkred** [comment]
No, as I've written, it also occurs in a clean FF40 stable profile, with only GM 3.3 and the script installed.
Also, my news feed has entries.

And the changeset of my Firefox 40 stable (windows) is 
https://hg.mozilla.org/releases/mozilla-release/rev/84e0a4087157 
(found in about:buildconfig)
in order to confirm that we use the same Firefox version.

**Comment by jerone** [comment]
> And in order to confirm that we use the same Firefox version:
> the changeset of my Firefox 40 stable (windows) is
> https://hg.mozilla.org/releases/mozilla-release/rev/84e0a4087157

Yeah same.

What I did noticed was that the "More" button doesn't recount the filters. But that still gives me 30 on all news feed.

I also notice that there are small changes to GitHub done today. Maybe they are in the progress of more changes.

**Comment by jerone** [comment]
What is the first item in your news feed? Maybe the first item is a new filter item that isn't supported yet...

**Comment by darkred** [comment]
The first item is this last comment of yours in this issue:
![http://i.imgur.com/Wtgr4aq.jpg](http://i.imgur.com/Wtgr4aq.jpg)

**Comment by jerone** [comment]
Can you do a HTML dump of all items with the `octicon-git-pull-request` icon. I'm still leaning to a news item that I've never seen before.

**Comment by darkred** [comment]
If I got it right, you want me to `document.getElementsByClassName("octicon-git-pull-request")`
which results as 
```
HTMLCollection [ 
<span.mega-octicon.octicon-git-pull-request>, 
<span.mega-octicon.octicon-git-pull-request>, 
<span.mega-octicon.octicon-git-pull-request> ]
````
and then click on each of these 3 elements and copy outer HTML of each entry. 
If this so, then it's this here: http://pastebin.com/vx4CTxTB



Also, all entries I have in news feed apart from https://github.com/jerone/UserScripts/
are from https://github.com/greasemonkey/greasemonkey/

**Comment by jerone** [comment]
So yeah, they changed something for PR news items. I don't have any PR items in my news list right now, but I'll try to find a fix for it. Thanks for helping finding the issue :purple_heart:

**Comment by darkred** [comment]
Glad to be of help.

**Comment by darkred** [comment]
Greetings, @jerone 

Unfortunately the issue has occured again:
all counters (in all three tabs of the script table, i.e. Actions/Repositories/Users) are zero.

There's no error in Console.


Using Tampermonkey 4.8.5867 in Chrome 70. Tested it with only TM running.
Here is a screenshot of my news feed:

<details>
<summary>Screenshhot</summary>

![2018-11-20_175822](https://user-images.githubusercontent.com/723651/48785754-07adc380-ecee-11e8-8b5a-beb53aab9e32.png)
</details>

**Comment by jerone** [comment]
I can confirm it, and they changed the HTML again. It looks like every `':scope > div > .body'` needs to be changed to `':scope > div > div > .body'. I'll try to find to time to make a fix soon (but a PR is always great).

**Comment by darkred** [comment]
Your suggestion fixes the issue. Thank you! 👍 

Here is the PR:
https://github.com/jerone/UserScripts/pull/140
