### ISSUE TITLE
(Github News Feed Filter) Add possibility to filter news by repo

### ISSUE THREAD

**Issue by apsavin** [jerone/UserScripts#70]
Hi, @jerone!
Thank you for your scripts a lot.
I want to suggest a new feature - add possibility to filter news by repo. I follow some too active repos and don't want to unfollow them because I want to recieve emails about activity in those repos. But their news make my github news feed useless. The situation is really better now, thanks to your userscript, but can be even better.)
What do you think about it?

**Comment by jerone** [comment]
Actually, I'm already working on this feature :smile: :+1: 

![2015-08-26 22_49_05-github](https://cloud.githubusercontent.com/assets/55841/9505792/bbcd6f3a-4c44-11e5-9fe3-21ed46459b9b.png)

You can follow progress here: https://github.com/jerone/UserScripts/tree/Github_News_Feed_Filter/Github_News_Feed_Filter

I still have to do all logic, which may take a while before I can finish it.
