### ISSUE TITLE
(Github Pages Linker) annoying "301 Moved Permanently" redirect

### ISSUE THREAD

**Issue by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [jerone/UserScripts#72]
i.e. as for now, https://jerone.github.io/Throbber.js is redirecting to https://jerone.github.io/Throbber.js/

---   47: var url = String.format("https://{0}.github.io/{1}", tree[1], tree[2]);
+++ 47: var url = String.format("https://{0}.github.io/{1}/", tree[1], tree[2]);

**Comment by jerone** [comment]
Issue confirmed. Fix confirmed. Can you tell why this is "annoying", as nobody will ever notice this happening.

ps. interesting name...

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
huh? redirect prevention? anyone?
but annoying rather by greasefork's "force find updates"-only design misconception, saying no to any useful customizing

**Comment by jerone** [comment]
I don't understand your comment, but this is an easy fix.

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
thanks, but what don't you understand exactly?
the first line was a quick irony about that this should be normal and nothing extreme or disgusting for statistically average developer trying to prevent any kind of spontaneous redirects (which will be requiring addional attention and thus some delays) with his/here browser setup, and the fact that i became the first nobody could be explained only by his/here personal busyness to laziness ratio
the second one pointed out that with greasefork you are or don't change script original code and receive update notification or do and lose active tracking possibility and get the one and only fully overwriting "force find updates" option i.e. in practice you still should to track manually (~with rss or with site monitors) your 10-50-100 slightly modified userscripts and that is quite opposite to what a helping mechanisms might be planned and embedded for, right? this attached bonus workarounding is what my "annoyingness" means
