### ISSUE TITLE
(GitHub Comment Enhancer) WIki have list of smiley not hided

### ISSUE THREAD

**Issue by Mte90** [jerone/UserScripts#75]
**Script**: GitHub Comment Enhancer
**Browser**: Firefox
**Addon**: GreaseMonkey
**Description**: When I edit a wiki page is showed the smiley list and is impossible edit the wiki.
For fix I use the inspector and add `display:none` on .suggester-container.

**Comment by jerone** [comment]
Thanks for reporting, this should be fixed in the next release, new version will probably be mirrored within minutes.
