### ISSUE TITLE
(Github News Feed Filter) Sync'd?

### ISSUE THREAD

**Issue by Martii** [jerone/UserScripts#76]
Just noticed this was updated a few hours back on GH and didn't show up [on OUJS](https://openuserjs.org/scripts/jerone/Github_News_Feed_Filter)... was this intentional?

Thanks.

**Comment by jerone** [comment]
> was this intentional?

Yes, the latest changes where on [another branch then main](https://github.com/jerone/UserScripts/tree/Github_News_Feed_Filter), which is part of a WIP [PR #71](https://github.com/jerone/UserScripts/pull/71).

**Comment by Martii** [comment]
Alrighty... just making sure there wasn't some missed fallout from the DB loss. Last update dates don't match your last release date on OUJS but that is a known issue from the restore and should self fix on your next release. Sorry to bother you.
