### ISSUE TITLE
(Github Comment Enhancer) Button styles wrong in gists

### ISSUE THREAD

**Issue by arthurhammer** [jerone/UserScripts#78]
This is in Google Chrome with Tampermonkey on OS X.

Some buttons have different heights and widths.

**How it looks in gists**:
<img width="734" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4521216/10122232/d3a7db50-6511-11e5-9e76-43613896a6fe.png">

**How it looks elsewhere**:
<img width="694" alt="screenshot - 2015-09-27 12 15 35" src="https://cloud.githubusercontent.com/assets/4521216/10122235/ea282a06-6511-11e5-8755-4fde73e24af7.png">

**Comment by jerone** [comment]
Already [working](https://github.com/jerone/UserScripts/tree/Github_Comment_Enhancer) on it :construction_worker: :smile:
