### ISSUE TITLE
(GitHub Comment Enhancer) inside the Emoji dropdown menu to add a link to Emoji Cheat Sheet

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#80]
I'd like to make this suggestion for this great script: 
inside the `Emoji` dropdown menu to add a link to [Emoji Cheat Sheet](http://www.emoji-cheat-sheet.com/), 
i.e. to the the list of all emojis supported.

Thank you

**Comment by jerone** [comment]
Thanks for your input! Aldo the Emoji Cheat Sheet is a very useful site (I've used it a few times before), I don't see any point in adding a link. The most useful feature from Emoji Cheat Sheet is the search, which this script also contains. Besides, maybe there are more useful sides and I don't want to fill this script with all kinds of useful links.
