### ISSUE TITLE
Github Comment Enhancer breaks Github's name completion

### ISSUE THREAD

**Issue by thomaslevesque** [jerone/UserScripts#81]
When you type "@", Github displays a list of suggestions to mention other people. When GCE is enabled, I can no longer pick a choice from this list with the keyboard, I have to use the mouse.

**Comment by jerone** [comment]
Thanks for reporting. I've noticed it too, never thought to link it to Github Comment Enhancer.
Same goes for emoji.

**Comment by jerone** [comment]
Wow, that was a hard one to fix. Hopefully tracked the cause down.

@thomaslevesque Any change you could test if the fix solves the problem for you too: https://github.com/jerone/UserScripts/blob/Github_Comment_Enhancer/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js (click <kbd>Raw</kbd> to install dev version).

**Comment by thomaslevesque** [comment]
@jerone, it works :)

Well done and thanks ! This bug was really annoying ;)

**Comment by jerone** [comment]
I'm working on another fix for using the keyboard on the toolbar dropdown buttons too. After that I'll release a new version of Github Comment Enhancer, so you can switch back to the live version.

**Comment by thomaslevesque** [comment]
OK, thanks!

**Comment by jerone** [comment]
Fixed and :ship:ed
