### ISSUE TITLE
(Github Image Viewer) regex pattern improvements + directory detection

### ISSUE THREAD

**Issue by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [jerone/UserScripts#82]
• with regexp: add .bmp format (e.g. https://github.com/quentinmrzt/Darlizot/tree/master/sprite), escape filetype dots and ignore the case (e.g. https://github.com/PeterLawrence/WinTimeStampUtility)
```udiff
--- _imageRegex: /(.jpe?g|.png|.gif|.ico|.tiff?)$/,
+++ _imageRegex: /(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i,
```
• with folders: check icon sibling for '.octicon-file-text' / !'.octicon-file-directory' class (e.g. https://github.com/github/octicons)
```udiff
if (target.classList && target.classList.contains("js-directory-link")
+++     && target.parentElement.parentElement.parentElement.firstElementChild.firstElementChild.classList.contains("octicon-file-text")
        && GithubImageViewer._imageRegex.test(target.href)) {
```

**Comment by jerone** [comment]
[**@jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1**](https://github.com/jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1) commented on [14 nov. 2015 05:30 CET](https://github.com/jerone/UserScripts/issues/82#issue-116894836 "2015-11-14T04:30:21Z - Replied by Github Comment Enhancer"):
> • with regexp: add .bmp format (e.g. https://github.com/quentinmrzt/Darlizot/tree/master/sprite), escape filetype dots and ignore the case (e.g. https://github.com/PeterLawrence/WinTimeStampUtility)
> ```udiff
> --- _imageRegex: /(.jpe?g|.png|.gif|.ico|.tiff?)$/,
> +++ _imageRegex: /(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i,
> ```

These changes are awesome! If you want credit you can send a PR. Otherwise I can make the changes if you want.

> • with folders: check icon sibling for '.octicon-file-text' / !'.octicon-file-directory' class (e.g. https://github.com/github/octicons)
> ```udiff
> if (target.classList && target.classList.contains("js-directory-link")
> +++     && target.parentElement.parentElement.parentElement.firstElementChild.firstElementChild.classList.contains("octicon-file-text")
>         && GithubImageViewer._imageRegex.test(target.href)) {
> ```

You mean when folders are named after image extensions?

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
[**@jerone**](https://github.com/jerone) commented on [Nov 14, 2015, 12:54 PM GMT+2](https://github.com/jerone/UserScripts/
issues/82#issuecomment-156683879 "2015-11-14T10:54:34Z - Replied by Github Comment Enhancer"):
> These changes are awesome! If you want credit you can send a PR. Otherwise I can make the changes if you want.

it will be very kind of you if you do everything by yourself
> You mean when folders are named after image extensions, including the dot?

yes, exactly: prevent GithubImageViewer from triggering by folders with names like "bmp"/".bmp"

**Comment by jerone** [comment]
[**@jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1**](https://github.com/jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1) commented on [14 nov. 2015 13:19 CET](https://github.com/jerone/UserScripts/issues/82#issuecomment-156691199 "2015-11-14T12:19:22Z - Replied by Github Comment Enhancer"):
> [**@jerone**](https://github.com/jerone) commented on [Nov 14, 2015, 12:54 PM GMT+2](https://github.com/jerone/UserScripts/
> issues/82#issuecomment-156683879 "2015-11-14T10:54:34Z - Replied by Github Comment Enhancer"):
> > You mean when folders are named after image extensions, including the dot?
> 
> yes, exactly: prevent GithubImageViewer from triggering by folders with names like "bmp"/".bmp"

I want to stay away from GitHub page elements as much as possible, definitely traveling up the tree and back down again. They change their page layout very often. I was thinking of extending the regex:

```diff
--- _imageRegex: /(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i,
+++ _imageRegex: /.*(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i,
```

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
> I want to stay away from GitHub page elements as much as possible ...

agree with such intentions, but unfortunately there no other way in code

> ... definitely traveling up the tree and back down again ...

3 ups to ".js-navigation-item" and ~ queryselector/queryselectorall[0] ".js-navigation-item .octicon-file-text" )

> ... They change their page layout very often. ...

once or twice per year during last few years or am I wrong? \*knocking on wood\*

> I was thinking of extending the regex:
> ```udiff
> --- _imageRegex: /(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i
> +++ _imageRegex: /.+(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i
> ```

ok, but it just simply excludes ".bmp"-named file or folder

**Comment by jerone** [comment]
[**@jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1**](https://github.com/jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1) commented on [14 nov. 2015 15:01 CET](https://github.com/jerone/UserScripts/issues/82#issuecomment-156698209 "2015-11-14T14:01:13Z - Replied by Github Comment Enhancer"):
> > I was thinking of extending the regex:
> > ```udiff
> > --- _imageRegex: /(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i
> > +++ _imageRegex: /.+(\.jpe?g|\.png|\.gif|\.bmp|\.ico|\.tiff?)$/i
> > ```
> 
> ok, but it just simply excludes ".bmp"-named file or folder

Anything named `X.bmp` for example. I can understand someone naming a folder `bmp` or `.bmp`, but a folder named `anything.bmp` seems far fetched.
I'm going to use the new regex, I can always change  to DOM traversing when more examples pop-up. Thanks for the improvements!

**Comment by jerone** [comment]
:clapper: Released new version of Github Image Viewer

**Comment by jP6a9b3OR6FN5mVP81pQ2aOrtfMhKEhaBX8WkP1** [comment]
the same to you
