### ISSUE TITLE
The "italic" button no longer works (but ctrl+i still works ok)

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#83]
After the latest update to v2.7.0 (in GM 2.6 in FF42) I noticed that, 
clicking the `italic` button (having selected text or not, it doesn't matter) doesn't work 
(but `ctrl+i` still works ok).

This is what I get in Browser Console:
`TypeError: definitionObject is undefined Github_Comment_Enhancer.user.js:416:1`

Thank you

**Comment by jerone** [comment]
Confirmed, will have a look.

**Comment by jerone** [comment]
Was a missed refactor in https://github.com/jerone/UserScripts/commit/9bf8974ad4203d7c2361a645405491c9903a9238, but this opened up a bigger issue where the wiki won't work anymore.

Going to revert most of that commit.

**Comment by jerone** [comment]
A fix for this :bug: and [more](https://github.com/jerone/UserScripts/issues/85) has been :ship:ed. 

Thanks for reporting!

**Comment by darkred** [comment]
You're welcome!
Thank you
