### ISSUE TITLE
(GitHub User Info) it doesn't show my set URL when mouseover on my avatar  (while using my everyday FF profile)

### ISSUE THREAD

**Issue by darkred** [jerone/UserScripts#84]
I've recently added a URL (https://greasyfork.org/en/users/2160-darkred) to my GitHub profile.
_(it appears ok in https://github.com/darkred)_
But, when mouseover on my avatar  (using my everyday FF profile) it doesn't show that URL.
I have already tried Options|Privacy|`clear recent history` in Firefox, 
and even loading e,g, this GitHub page with cache disabled,
but it didn't help.

This is what is displayed in Browser Console while mouseover: 

```
GithubUserInfo:avatar timeout                                     Github_User_Info.user.js:592
GithubUserInfo:getData CACHED <unavailable>                       Github_User_Info.user.js:356
GithubUserInfo:fillData <unavailable> <unavailable> <unavailable> Github_User_Info.user.js:492
```

On the other hand, in a clean 42 profile with only GM 3.6 installed, the URL is showed ok.

What could I do to make it show the URL in the avatar again?
Thank you

**Comment by jerone** [comment]
To not flood both GitHub and [your account](https://api.github.com/rate_limit) with user info requests, I've added [caching for 7 days](https://github.com/jerone/UserScripts/blob/master/Github_User_Info/Github_User_Info.user.js#L326).

There's currently no simple way of deleting the cached user info, without editing the userscript or GM database, as `GM_setValue` is used.

Did you update your profile more then 7 days ago?

**Comment by darkred** [comment]
No, it's more recently, for sure.

**Comment by jerone** [comment]
Oke, so then you have to wait until the 7 days are past or edit the userscript and execute the following code (untested):
```
var usersString = GM_getValue('users', '{}');
var users = JSON.parse(usersString);
delete users["darkred"];
GM_setValue('users', JSON.stringify(users));
```
_Don't forget to force update again, so automatic updates are enabled again._

**Comment by darkred** [comment]
Yes, your code fixed it.
Thanks a lot for the quick answer!
