### ISSUE TITLE
(Github Comment Enhancer) Clicking on the smiley button takes quite long

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#87]
![smileyclick](https://cloud.githubusercontent.com/assets/11966684/11615836/847c34ea-9c6b-11e5-9055-67e43cab9abd.gif)

**Comment by jerone** [comment]
Confirmed. It's kind of intentional, the whole list is AJAX fetched and then attached to the DOM. To not overload GitHub and block the page every time this userscript is loaded, the whole list is only loaded on emoji button click.

**Comment by rugk** [comment]
Okay, I see (this also in the developer console).
So what about:
1. at first only displaying the text and later loading the images
2. only load the images of the smilies currently displayed (as you really seem to load all smileys, you may rather try to load only the images which are shown)

**Comment by jerone** [comment]
I'll have a second look if I can improve loading time of the emoji dropdown.

**Comment by jerone** [comment]
Closing in favor of https://github.com/jerone/UserScripts/issues/106
