### ISSUE TITLE
(Github Comment Enhancer) When the smiley buttons clicked you cannot drag & drop files to upload them

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#88]
Actually you can, but is the wrong input field... :laughing: 
![clickdraganddrop](https://cloud.githubusercontent.com/assets/11966684/11615853/f17f87b8-9c6b-11e5-8e46-0b379ba79914.gif)

**Comment by jerone** [comment]
Why do you want to drag and drop to upload? Just clicking the emoji will insert the correct emoji code tag that GFM will convert into an image.

**Comment by rugk** [comment]
It is supported - but in the wrong input field. :wink:

**Comment by jerone** [comment]
Aldo I recognize the issue, I'm not going to try fix this for two reasons. 1. This is a bug from GitHub as the same happens when opening any dropdown menu. 2. Closing is just one click or key away. Thanks for reporting!

**Comment by rugk** [comment]
> 1. This is a bug from GitHub as the same happens when opening any dropdown menu

Okay, but as they do not have dropdown menus by default on their comment part you cannot really blame them...

**Comment by jerone** [comment]
[**@rugk**](https://github.com/rugk) commented on [9 dec. 2015 18:31 CET](https://github.com/jerone/UserScripts/issues/88#issuecomment-163333285 "2015-12-09T17:31:23Z - Replied by Github Comment Enhancer"):
> > 1. This is a bug from GitHub as the same happens when opening any dropdown menu
> 
> Okay, but as they do not have dropdown menus by default on their comment part you cannot really blame them...

The kind of do. When admin of a repo, the labels, milestones and assignee all overlap the comment field, but more importantly they create some kind of overlay preventing dropping a file besides the menu.

**Comment by rugk** [comment]
> When admin of a repo, the labels, milestones and assignee all overlap the comment field

Ah did not thought of these dropdowns... :smile: 
They are much more far away from the comment field than the dropdown by this script. :smiley: 

> but more importantly they create some kind of overlay preventing dropping a file besides the menu.

Okay, yes this an issue. Have you already reported this to GitHub?

**Comment by rugk** [comment]
Done.

And just discovered https://github.com/jerone/UserScripts/issues/91... :smile:

**Comment by rugk** [comment]
Reply from GitHub support:
> Thanks for the report! I'm seeing the same thing - we can't promise if or when the behavior might change, but we'll mention this to our front end folks for investigation.
