### ISSUE TITLE
(Github JSON Dependencies Linker) composer.json support

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#89]
See https://getcomposer.org/, https://packagist.org/ and [Wikipedia](https://en.wikipedia.org/wiki/Composer_%28software%29).

**Comment by jerone** [comment]
Can you reply a link to a composer.json example file on GitHub...

**Comment by rugk** [comment]
I think there are already many example files, but here you go:
* https://github.com/rugk/threema-msgapi-sdk-php/blob/master/composer.json
* https://github.com/paragonie/halite/blob/4cd2debc6dd2bd9ca3e87374750fa60c67f8d712/composer.json

**Comment by jerone** [comment]
I'm new to this composer... 

* Is it always called `composer.json`?
* What first-level key does this userscript has to look for? I couldn't find any of the [supported](https://github.com/jerone/UserScripts/blob/master/Github_JSON_Dependencies_Linker/Github_JSON_Dependencies_Linker.user.js#L52-L58) keys.
* Which domain has to be used for linking?

**Comment by rugk** [comment]
Generally I'd recommend having a look here: https://getcomposer.org/doc/04-schema.md

About your questions:
> Is the file always called composer.json?

Yes.

> What first-level key does this userscript has to look for? I couldn't find any of the supported keys.

I think you should look for `require` and other ["package links"](https://getcomposer.org/doc/04-schema.md#package-links).

> Which domain has to be used for linking?

I think always packagist.org. E.g. you can find `threema-msgapi-sdk-php` [here](https://packagist.org/packages/rugk/threema-msgapi-sdk-php).
