### ISSUE TITLE
(Github Comment Enhancer) Shown on GitHub contact page, but does not work

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#91]
This script shows its toolbar on the GitHub [contact page](https://github.com/contact) but it does not work there because no matter on what button you click it does nothing except jumping to the top of the page.

**Comment by jerone** [comment]
Confirmed. 

Seeing that attaching files is supported, GFM is probably also supported in their support message. 
Instead of removing the toolbar from that page, I'll try to make it there too.

**Comment by rugk** [comment]
Thx. It works now.
