### ISSUE TITLE
(Github Pull Request From Link) Underlines `:` and marks it

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#93]
It's best to show it like this:
![underlines](https://cloud.githubusercontent.com/assets/11966684/11727102/2eb6f986-9f82-11e5-8ffb-9bc14703e351.gif)
![markstext](https://cloud.githubusercontent.com/assets/11966684/11727103/2ebb405e-9f82-11e5-9a77-f4097c0fa951.gif)

used https://github.com/jerone/UserScripts/pull/12
Firefox 42.0

**Comment by jerone** [comment]
> Underlines `:`

I kind of left this intentionally to let users know that's a link now.

> and marks it

This is somewhat a feature from GitHub. If you disable the userscript it lets you select the whole user+branch, I guess for easy coping. Now that this is a link, GitHub's feature is probably unnecessary.

**Comment by rugk** [comment]
[**@jerone**](https://github.com/jerone) commented on [10. Dez. 2015, 21:45 MEZ](https://github.com/jerone/UserScripts/issues/93#issuecomment-163744390 "2015-12-10T20:45:05Z - Replied by Github Comment Enhancer"):
> I kind of left this intentionally to let users know that's a link now.

But as  you can see it is really *only* the character `:` (and this character is not in every PR). I mean should not it be either the whole branch name or not be underlined at all?

> This is somewhat a feature from GitHub. If you disable the userscript it lets you select the whole user+branch, I guess for easy coping. Now that this is a link, GitHub's feature is probably unnecessary.

Ah not really in my test:
![withoutuserscript](https://cloud.githubusercontent.com/assets/11966684/11728244/10fa68fe-9f89-11e5-971e-946edc0c9e67.gif)

However I also could not reproduce the marking with your userscript anymore after I reenabled this...

**Comment by jerone** [comment]
> Ah not really in my test:

You have to click left from the username. It's kind of a bug that this feature doesn't work on children of an `.user-select-contain` element (probably a left-over from latest site update)...
```
$(document).on("click", ".user-select-contain", function() {
        var t, n;
        n = window.getSelection(),
        n.rangeCount && (t = n.getRangeAt(0).commonAncestorContainer,
        e(this, t) || n.selectAllChildren(this))
    }))
```

> However I also could not reproduce the marking with your userscript anymore after I reenabled this...

After navigating to another page and back the feature is back again (probably also a bug).

**Comment by rugk** [comment]
> You have to click left from the username.

Eh, what?
I clicked everywhere there and it did not worked. (just tried it again)

However this does not really matter as I do not want to use it anyway. :smiley:
