### ISSUE TITLE
Suggestion for new script: Pull Requests Do Not Merge

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#94]
I tried to find a simple userscript which disables the merge button in PRs if they are labelled with "Do not merge"/"Don't merge"/"[DNM]" or something similar.
I think somewhere I already saw a Firefox addon [like this](https://addons.mozilla.org/en-US/firefox/addon/github-fixed/) which does this, but I think with a userscript this is much nicer anyway. :smiley:

**Comment by rugk** [comment]
Another example: https://github.com/sanemat/do-not-merge-wip-for-github

**Comment by jerone** [comment]
Personally I don't see the use of this feature. If you don't want to merge WIP PR's then don't press the merge button. If it were possible as PR author to disable the merge button, that would make more sense, but that requires an site update. You probably have more luck asking for an [Firefox/Userscript](https://github.com/sanemat/do-not-merge-wip-for-github/issues/78) port on above linked Chrome extension.
