### ISSUE TITLE
(Github Comment Enhancer) Disable localized time zone?

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#96]
When quoting comments how does it get out what time zone to use? Does it always try to use the local one?

I would like to have an option to use UTC instead.

**Comment by jerone** [comment]
[GCE](https://github.com/jerone/UserScripts/tree/master/Github_Comment_Enhancer#readme Github Comment Enhancer) uses what GitHub supplies in the timestamps' title attribute, provided by the [`<time>` web component extension](https://github.com/github/time-elements). According their documentation, "_lets the browser choose how to localize the displayed time according to the user's preferences_". GCE doesn't do any time calculations itself. I'm going to look into their docs if it's possible to calculate a new time that isn't localized.

**Comment by jerone** [comment]
Note to self:
```js
var x =new window.RelativeTimeElement("2016-01-05T19:09:05Z")
//document.body.appendChild(x);
x.dateTime = "2016-01-05T19:09:05Z";
//x.attributeChangedCallback("datetime", undefined, "2016-01-05T19:09:05Z");
x.createdCallback();
console.log(x);
```

**Comment by jerone** [comment]
Closing this issue as Github Comment Enhancer is deprecated.
