### ISSUE TITLE
(Github Comment Enhancer) Serious performance issues in Firefox

### ISSUE THREAD

**Issue by thomaslevesque** [jerone/UserScripts#97]
I was wondering why Firefox always froze when I opened a PR in GitHub, and I realized that it worked fine when I disabled GreaseMonkey. Since GCE is the only user script I installed, I'm afraid it's the culprit...

Note that it works fine in Chrome.

**Comment by jerone** [comment]
Hi. I'm sorry to hear to you've got problems. I can't confirm any performance issues as I just created a [few PR's](https://github.com/suda/tool-bar/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ajerone+) in the last hour without problem. Can you give me some more information, beginning with version of the userscript, FF, GM...

Also can you check if any related errors appear in the Browser Console (Menu > Developer > Browser Console).

**Comment by thomaslevesque** [comment]
Hi,

I'm using FF 43.0.4, GM 3.6 and GCE 2.8.3. Here's an example of a PR for which the browser freezes temporarily: https://github.com/FakeItEasy/FakeItEasy/pull/574. In general, the larger the PR, the longer the freeze, and that one is pretty big.

Here's the console output:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-9ee55ceaf87fc34dc86334249fef6cbece88e815478e0fbe81642d57ed0fff89.js:1:20147
Empty string passed to getElementById(). github-394e52ce754d3bfd2289c98e49302efbad2b1ddb5c40d88f0b4b68088f2a74cd.js:6:10437
Firefox can't establish a connection to the server at wss://live.github.com/_sockets/MTg2NDI4MTo3OGZjMDE4OTYxZjVjMjhkMjg2NTU0YzFiMzM3OTg5YjoyZWNhMDQ2MmQ1MDNhZGE0YmZhYjZlYjQ4NTJkMDk3MTdjNGRhYzZmMTA1Y2Q0NWI3ZDJkMTkwZTBlMWVhYjRi--2ca2126eb698cbd1730175f9ddda7d4dbc5c1be6. github-394e52ce754d3bfd2289c98e49302efbad2b1ddb5c40d88f0b4b68088f2a74cd.js:5:25141
The connection to wss://live.github.com/_sockets/MTg2NDI4MTo3OGZjMDE4OTYxZjVjMjhkMjg2NTU0YzFiMzM3OTg5YjoyZWNhMDQ2MmQ1MDNhZGE0YmZhYjZlYjQ4NTJkMDk3MTdjNGRhYzZmMTA1Y2Q0NWI3ZDJkMTkwZTBlMWVhYjRi--2ca2126eb698cbd1730175f9ddda7d4dbc5c1be6 was interrupted while the page was loading. github-394e52ce754d3bfd2289c98e49302efbad2b1ddb5c40d88f0b4b68088f2a74cd.js:5:25141
```

**Comment by jerone** [comment]
> Here's the console output:

Those errors seem unrelated to GCE.

> Here's an example of a PR for which the browser freezes temporarily: FakeItEasy/FakeItEasy#574.

And when do you have problems with freezes?:

1. When navigating to this PR from another Github page?
2. When navigating to this PR in a new tab (no history)?
3. When navigating in this PR from Conversation to Commits?
4. When navigating in this PR from Conversation to Files changed?

**Comment by thomaslevesque** [comment]
Every time I navigate to the page, whether it's in a new tab or when navigating from another page. Switching to the Files changed tab is even worse, sometimes freezing for more than 10s and showing the "long running  script" dialog

**Comment by jerone** [comment]
This might be related to changes to the website: https://github.com/jerone/UserScripts/issues/98

**Comment by thomaslevesque** [comment]
> This might be related to changes to the website: #98

I don't think so; I noticed this problem a while ago, before Github introduced its toolbar.

**Comment by mzso** [comment]
Hmmm I re-enabled this addon to make a comment, but now it doesn't seem to work at all. None of the features seem to appear. eg: I can't quote with a reply.
By the way I'm on aurora and have e10s enabled.
(PS I opened #104 )

**Comment by jerone** [comment]
Yeah it appears that Github changed their site again, completely breaking this (and other) userscript.

**Comment by thomaslevesque** [comment]
> Yeah it appears that Github changed their site again, completely breaking this (and other) userscript.

I can confirm. I had been using my own userscript for a while (it just mapped custom keyboard shortcuts to the standard Github formatting buttons), and now it's broken as well.

**Comment by jerone** [comment]
Closing in favor of https://github.com/jerone/UserScripts/issues/106
