### ISSUE TITLE
(Github Comment Enhancer) Integrate into GitHubs new own buttons

### ISSUE THREAD

**Issue by rugk** [jerone/UserScripts#98]
You probably already read it: [GitHub enhanced it's Markdown commenting system](https://github.com/blog/2097-improved-commenting-with-markdown)

With your userscript we now have duplicated buttons with the same function, so this is not really good. So you might want to adjust your userscript to fit to the new GitHub update.

**Comment by jerone** [comment]
Thanks for the heads-up. This requires a complete overhaul of GCE. Not sure what I'm going to do next...

Do you think the new toolbar is sufficient or do you miss something that GCE provides?

**Comment by rugk** [comment]
What's still missing by default in GitHubs buttons is:
* the easy code syntax selection
* the snippets
* the emoticons (although this had some performance issues (https://github.com/jerone/UserScripts/issues/87) anyway) 
* underline
* strikethough

And you cannot use GitHubs new toolbar when editing a wiki site.

**Comment by jerone** [comment]
Thank you for your input!

For me the missing features I use are:

- strikethrough
- link popup
- clear
- comment reply

**Comment by thomaslevesque** [comment]
The feature I miss from Github's toolbar is the keyboard shortcuts. Only a few commands have shortcuts:
- <kbd>Ctrl</kbd> + <kbd>I</kbd>: italic
- <kbd>Ctrl</kbd> + <kbd>B</kbd>: bold
- <kbd>Ctrl</kbd> + <kbd>K</kbd>: link (which is annoying, because I'm used to this shortcut being for "code", like in GCE and StackOverflow)

**Comment by PhiLhoSoft** [comment]
Actually, I would just disable entirely GitHub's toolbar and rely only on the one your create... :grin: If it is in the power of GM.

A major annoyance with the new feature is conflicting key shortcuts: when I use Ctrl+K (the most common for me), eg. around 'with', I get 

    [`with` ](url)

which is a pain... At least, Undo (Ctrl+Z) leaves only the wanted code markup...

**Comment by jerone** [comment]
I'm kind of leaning towards separating the reply feature out of GCE and making that a separate userscript. That part still works and can work with GitHub's new toolbar.

For making GCE working again I'm still not sure what do yet...

1. I can extend GitHub's toolbar with the missing features.
2. I can replace GitHub's toolbar with GCE features.
3. Remove GitHub's toolbar and keep things as is.

Option 2 & 3 relatively aren't very much work. Option 1 is probably more work. Then there's the choice to follow GitHub's new buttons design or not...

**Comment by rugk** [comment]
Now the buttons really look broken:
![brokenlayout](https://cloud.githubusercontent.com/assets/11966684/12724134/d6413280-c90c-11e5-8776-f9f004aef4df.PNG)

**Comment by jerone** [comment]
Even the reply button isn't working anymore :(

**Comment by jerone** [comment]
Looks like they moved away from glyph fonts and are using SVG now for all icons.

**Comment by joeytwiddle** [comment]
I don't know why they didn't just install your userscript on their site! :heart:

**Comment by Trubbel** [comment]
First of all, thank you for making my (and everyone else) life easier with this userscript. Have been using it for quite some time now.

Anyway, me personally would prefer _option 3_, as that's the one I'm (we?) most used to. It also looks generally better with the buttons above the textare rather than in the tabs.

**Comment by mikhoul** [comment]
I would go with option #2 since bypassing Github toolbar will resolve the issue for a long time.

![http://i.imgur.com/0vXIbUh.png](http://i.imgur.com/0vXIbUh.png)

**Comment by rugk** [comment]
I think the new GitHub toolbar looks quite good and it saves space. And as only a few features are missing in this new toolbar I'm fine with options 1 or two.

**Comment by jerone** [comment]
Just a heads-up to all; I'm slowly working on [option 3](https://github.com/jerone/UserScripts/issues/98#issuecomment-176787857).

**Comment by jerone** [comment]
I've put a [PR](https://github.com/jerone/UserScripts/issues/100) online for following the current progress. If people want to test they can download the raw version of the [userscript](https://github.com/jerone/UserScripts/blob/Github_Comment_Enhancer/Github_Comment_Enhancer/Github_Comment_Enhancer.user.js). I'm going to test it a little more before merging the PR.

**Comment by rinopo** [comment]
Hi, 
Thanks a lot for the great userscript!

The version 2.8.3 seems to wipe other add-on's functionality which tries to add buttons to GitHub's native toolbar.

"[GitHub Canned Responses](https://github.com/notwaldorf/github-canned-responses)" is an example of such add-on.

**Comment by jerone** [comment]
@rinopo Supporting other addons isn't on the roadmap for now. Please open another issue so I can have a look at it later.

**Comment by rinopo** [comment]
Thanks for the reply. Point taken.

**Comment by PhiLhoSoft** [comment]
Looks `fine`! I am **happy** to see this _fine_ script to work again! :smiley:
I see you now use the ~~new~~ SVG icons (<ins>octicon</ins>) of [GitHub](https://github.com/j)... :grinning:
Code fences?
```
<div ng-if="loggedIn" class="content-container">
	<div ui-view="leftPanel"  class="side-panel left"  role="region"></div>
	<div ui-view              class="page-content"     role="region"></div>
	<div ui-view="rightPanel" class="side-panel right" role="region"></div>
</div>
```
Yup, OK too. Can't tell it is a thorough test, but keyboard shortcuts and toolbar icons work fine.
Thanks for your work.

**Comment by jerone** [comment]
I released the new version of GCE aldo I'm noticing that GitHub is still making changes to the website.

**Comment by Trubbel** [comment]
@jerone Thank you so much!

**Comment by rugk** [comment]
Nice, but I'm also in favour of separating the "reply feature" into a single user script or at least making it configurable. Because now there may be users who would like to use GItHubs new toolbar, but still like to use your reply feature.
It would be nice if this could be separated...
